# ============
# Dependencias
# ============
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install


# ===================
# Builder - Crear app
# ===================
FROM node:21-alpine3.19 as builder

WORKDIR /usr/src/app

# copiar de deps modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

# copiar todo el codigo fuente de la app (menos el dockerignore)
COPY . .

RUN npm run build

# limpiar cache y dependencias de dev, solo quedo con las de prod
RUN npm ci -f --only=production && npm cache clean --force

RUN npx prisma generate

# ============
# Imagen final
# ============
FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

# copiar carpeta dist
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]